#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

if [[ (( $+commands[nvim] )) ]]; then
  alias vi='nvim'
  alias vim='nvim'
fi

if [[ (( $+commands[emacs] )) ]]; then
  emacst () { $commands[emacs] -nw $* }
  emacs ()  { $commands[emacs] $* &>/dev/null &| }
  alias et='emacst'
  EDITOR='emacst'
  VISUAL='emacst'
elif [[ (( $+commands[nvim] )) ]]; then
  EDITOR='nvim'
  VISUAL='nvim'
else
  EDITOR='vi'
  VISUAL='vi'
fi

export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)


# interactive sessions only
if [[ -o LOGIN ]]; then
  # direnv
  [[ -d $HOME/.local/bin ]] && path=( $path $HOME/.local/bin )
  (( $+commands[direnv] )) && eval "$(direnv hook zsh)"

  # roswell (lisp)
  (( $+commands[ros] )) && path=( $path $HOME/.roswell/bin )

  # go
  (( $+commands[go] )) && path=( $path $(go env GOPATH)/bin )

  # doom emacs
  [[ -x $HOME/.emacs.d/bin/doom ]] && path=( $path $HOME/.emacs.d/bin )
fi


#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'
#export LESS='-F -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
